language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7

before_install:
  - git submodule update --remote

install:
  - pip install flake8
  - pip install ipython
  - pip install ipythonblocks
  - pip install ipywidgets
  - pip install keras
  - pip install matplotlib
  - pip install networkx
  - pip install numpy
  - pip install opencv-python
  - pip install Pillow
  - pip install pytest-cov
  - pip install qpsolvers
  - pip install quadprog
  - pip install six
  - pip install sortedcontainers
  - pip install tensorflow

script:
  - py.test --cov=./
  - python -m doctest -v *.py

after_success:
  - flake8 --max-line-length 100 --ignore=E121,E123,E126,E221,E222,E225,E226,E242,E701,E702,E704,E731,W503 .

notifications:
  email: false
